spring.application.name=workerHandler

server.port=4001

#spring.datasource.url=jdbc:mysql://10.118.16.2:3306/ongoing-renders?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.url=jdbc:mysql://localhost:3309/ongoing-renders?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
#Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

gcs.BucketName=jackfruit-bucket
gcs.ProjectId=blendit-jackfruit

security.jwt.secret-key=${JWT_SECRET_KEY}

#----------RabbitMQ-------------#
#spring.rabbitmq.host=definition
#spring.rabbitmq.port=5672
#spring.rabbitmq.username=username
#spring.rabbitmq.password=password

spring.rabbitmq.host=localhost

spring.rabbitmq.port=5672
#spring.rabbitmq.username=username
#spring.rabbitmq.password=password

spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Listener config (important for manual ack)
spring.rabbitmq.listener.simple.acknowledge-mode=manual