spring.application.name=workerHandler

server.port=4001

spring.datasource.url=jdbc:mysql://localhost:3309/ongoing-renders?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=secret
#Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

gcs.BucketName=jackfruit-bucket
gcs.ProjectId=blendit-jackfruit

security.jwt.secret-key=148ea99d07eaf5c012e37afac84eeeef4f9af015ae40eaebf67c9ac348594adb

#----------RabbitMQ-------------#
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Listener config (important for manual ack)
spring.rabbitmq.listener.simple.acknowledge-mode=manual