spring.application.name=workerHandler

server.port=${PORT:8080}

# spring.datasource.url=jdbc:mysql://10.118.16.2:3306/ongoing-renders?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
# #spring.datasource.url=jdbc:mysql://localhost:3309/ongoing-renders?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
# spring.datasource.username=${DB_USERNAME}
# spring.datasource.password=${DB_PASSWORD}
# #Hibernate


# --- Cloud SQL MySQL ---
spring.datasource.url=jdbc:mysql:///ongoing-renders
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.hikari.data-source-properties.socketFactory=com.google.cloud.sql.mysql.SocketFactory
spring.datasource.hikari.data-source-properties.cloudSqlInstance=${CLOUD_SQL_CONNECTION_NAME}


spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false


gcs.BucketName=jackfruit-bucket
gcs.ProjectId=blendit-jackfruit

security.jwt.secret-key=${JWT_SECRET_KEY}

#----------RabbitMQ-------------#
#spring.rabbitmq.host=definition
#spring.rabbitmq.port=5672
#spring.rabbitmq.username=username
#spring.rabbitmq.password=password

# spring.rabbitmq.host=localhost

# spring.rabbitmq.port=5672
# #spring.rabbitmq.username=username
# #spring.rabbitmq.password=password

# spring.rabbitmq.username=guest
# spring.rabbitmq.password=guest

# ----------RabbitMQ------------- #
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT:5672}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD}

# Listener config (important for manual ack)
spring.rabbitmq.listener.simple.acknowledge-mode=manual

# gcloud run deploy worker-handler-cloud-build --image gcr.io/blendit-jackfruit/worker-handler-cloud-build:latest --region us-central1 --platform managed --allow-unauthenticated --set-env-vars "DB_USERNAME=root,DB_PASSWORD=IhaveA2Bpencil#,JWT_SECRET_KEY=148ea99d07eaf5c012e37afac84eeeef4f9af015ae40eaebf67c9ac348594adb,CLOUD_SQL_CONNECTION_NAME=blendit-jackfruit:us-central1:auth-mysql-1,SPRING_RABBITMQ_HOST=10.128.0.10,SPRING_RABBITMQ_PORT=5672,SPRING_RABBITMQ_USERNAME=username,SPRING_RABBITMQ_PASSWORD=password" --add-cloudsql-instances blendit-jackfruit:us-central1:auth-mysql-1 --vpc-connector rabbitmq-connector --vpc-egress=private-ranges-only