spring.application.name=stats

server.port=4009

spring.datasource.url=jdbc:mysql://localhost:3310/statsdb?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=secret
#Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false


#----------RabbitMQ-------------#
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Listener config (important for manual ack)
spring.rabbitmq.listener.simple.acknowledge-mode=auto